In [1]:
import numpy as np

# Создание массив NumPy 3x3 от 1 до 9
arr = np.arange(1, 10).reshape((3, 3))

arr = arr * 2

# Заменяем все элементы больше 10 на 0
arr[arr > 10] = 0

print(arr)


[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]
