In [1]:
import numpy as np

# единич матрица  4x4
identity_matrix = np.identity(4)

print("Единичная матрица:\n", identity_matrix)

# диаг матрица  4x4 с заданными диагональными элементами
diagonal_matrix = np.diag([5, 10, 15, 20])

print("\nДиагональная матрица:\n", diagonal_matrix)

# сумма всех элементов единич матрицы
identity_sum = np.sum(identity_matrix)

#  сумма всех элементов диаг матрицы
diagonal_sum = np.sum(diagonal_matrix)

print("\nСумма элементов единичной матрицы:", identity_sum)
print("Сумма элементов диагональной матрицы:", diagonal_sum)

# Сравнение
if identity_sum > diagonal_sum:
    print("\nСумма элементов единичной матрицы больше суммы элементов диагональной матрицы.")
elif identity_sum < diagonal_sum:
    print("\nСумма элементов единичной матрицы меньше суммы элементов диагональной матрицы.")
else:
    print("\nСуммы элементов обеих матриц равны.")



Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]

Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50

Сумма элементов единичной матрицы меньше суммы элементов диагональной матрицы.
