In [1]:
import numpy as np

matrix1 = np.random.randint(1, 21, (3, 3))  
matrix2 = np.random.randint(1, 21, (3, 3))

print("Матрица 1:\n", matrix1)
print("\nМатрица 2:\n", matrix2)

sum_matrix = matrix1 + matrix2

#  разность 
diff_matrix = matrix1 - matrix2

#  поэлементное умножение 
elementwise_product = matrix1 * matrix2

print("\nСумма :\n", sum_matrix)
print("\nРазность :\n", diff_matrix)
print("\nПоэлементное произведение :\n", elementwise_product)



Матрица 1:
 [[19 16 14]
 [14 16 17]
 [ 4  8  7]]

Матрица 2:
 [[ 4  8 15]
 [10 13 16]
 [18 16  8]]

Сумма :
 [[23 24 29]
 [24 29 33]
 [22 24 15]]

Разность :
 [[ 15   8  -1]
 [  4   3   1]
 [-14  -8  -1]]

Поэлементное произведение :
 [[ 76 128 210]
 [140 208 272]
 [ 72 128  56]]
