In [1]:
import numpy as np

# 2x3, со случайными числами от 1 до 10
matrix1 = np.random.randint(1, 11, (2, 3))

# 3x2, со случайными числами от 1 до 10
matrix2 = np.random.randint(1, 11, (3, 2))

print("Матрица 1:\n", matrix1)
print("\nМатрица 2:\n", matrix2)

# умножение с оператором @
product_matrix = matrix1 @ matrix2  

print("\nРезультат умножения:\n", product_matrix)


Матрица 1:
 [[7 6 2]
 [5 7 2]]

Матрица 2:
 [[ 4  8]
 [ 1  6]
 [10  1]]

Результат умножения:
 [[54 94]
 [47 84]]
