In [1]:
import numpy as np
import numpy.linalg as la

# 3x3
matrix = np.random.rand(3, 3)

print("Исходная матрица:\n", matrix)

# определитель
determinant = la.det(matrix)

print("\nОпределитель матрицы:", determinant)

# Проверка, матрица вырожденная или не (определитель равен 0)если 0 то ничего не будетб
if np.isclose(determinant, 0): 
    print("\nМатрица вырождена, обратной матрицы не существует.")
else:
    # обратная матрицу
    inverse_matrix = la.inv(matrix)

    print("\nОбратная матрица:\n", inverse_matrix)


Исходная матрица:
 [[0.1261026  0.36782876 0.2696788 ]
 [0.00192422 0.00896292 0.5537988 ]
 [0.44902583 0.83598093 0.79023471]]

Определитель матрицы: 0.03276915463449463

Обратная матрица:
 [[-1.39119372e+01 -1.99043042e+00  6.14254520e+00]
 [ 7.54213473e+00 -6.54337733e-01 -2.11529857e+00]
 [-7.37270767e-02  1.82321594e+00  1.28921596e-02]]
