In [1]:
import numpy as np

#  4x4, со случайными целыми числами от 1 до 50
matrix = np.random.randint(1, 51, (4, 4))

print("Исходная матрица:\n", matrix)

# транспонированная (вычисление)
transposed_matrix = matrix.T  

print("\nТранспонированная матрица:\n", transposed_matrix)

# след матрицы
trace = np.trace(matrix)

print("\nСлед матрицы:", trace)


Исходная матрица:
 [[45  9 46 15]
 [48  8 20 47]
 [30 21 16 42]
 [35 34 24  3]]

Транспонированная матрица:
 [[45 48 30 35]
 [ 9  8 21 34]
 [46 20 16 24]
 [15 47 42  3]]

След матрицы: 72
